name: Dependency Submission

on:
  push:
    branches: [ "main", "release_**" ]
    paths:
      - '**/build.gradle'
      - 'build.gradle'
      - '**/*.gradle'
      - 'gradle.properties'
      - 'settings.gradle'
  pull_request:
    paths:
      - '**/build.gradle'
      - 'build.gradle'
      - '**/*.gradle'
      - 'gradle.properties'
      - 'settings.gradle'
  workflow_dispatch:

permissions:
  contents: write
  security-events: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adopt'
          
      - name: Clear existing dependency graph
        run: |
          curl -L \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/dependency-graph/snapshots
          
      - uses: mikepenz/gradle-dependency-submission@v0.9.1
        with:
          gradle-project-path: .
          gradle-build-module: |-
            :
            :utils
            :abi
            :core
