name: Dependency Submission

on:
  push:
    branches: [ "main", "release_**" ]
    paths:
      - '**/build.gradle'
      - 'build.gradle'
      - '**/*.gradle'
      - 'gradle.properties'
      - 'settings.gradle'
  pull_request:
    paths:
      - '**/build.gradle'
      - 'build.gradle'
      - '**/*.gradle'
      - 'gradle.properties'
      - 'settings.gradle'
  workflow_dispatch:

permissions:
  contents: write
  security-events: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adopt'
          
      - name: Clear existing dependency graph
        run: |
          curl -L \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/dependency-graph/snapshots
          
      - uses: mikepenz/gradle-dependency-submission@v0.9.1
        with:
          gradle-project-path: .
          gradle-build-module: |-
            :
            :utils
            :abi
            :core

      - name: Generate and save dependency graph
        uses: gradle/actions/dependency-submission@v4
        with:
          # Use a particular Gradle version instead of the configured wrapper.
          gradle-version: 8.6
  
          # The gradle project is not in the root of the repository.
          build-root-directory: tools/gradlew
  
          # Choose a task that will trigger dependency resolution
          dependency-resolution-task: myDependencyResolutionTask
  
          # Additional arguments that should be passed to execute Gradle
          additional-arguments: --no-configuration-cache
  
          # Enable configuration-cache reuse for this build.
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
  
          # Do not attempt to submit the dependency-graph. Save it as a workflow artifact.
          dependency-graph: generate-and-upload
  
          # Change the number of days that workflow artifacts are retained. (Default is 30 days).
          artifact-retention-days: 5
  
          # Specify the location where dependency graph files will be generated.
          dependency-graph-report-dir: custom-report-dir
  
          # By default, failure to generate a dependency graph will cause the workflow to fail
          dependency-graph-continue-on-failure: true
